# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': '\u57ce\u5e02',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departname', models.CharField(max_length=10, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=10, unique=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xbc\x96\xe5\x8f\xb7')),
                ('describe', models.CharField(blank=True, default=b'', max_length=30, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('buy_date', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe9\x87\x87\xe8\xb4\xad\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_use', models.NullBooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x9c\xa8\xe7\x94\xa8')),
                ('suplier', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hardware.City')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart')),
            ],
            options={
                'verbose_name': '\u786c\u4ef6',
                'verbose_name_plural': '\u7535\u8111',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default=b'', max_length=10, unique=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('price', models.IntegerField(default=0, verbose_name=b'\xe4\xbb\xb7\xe6\xa0\xbc')),
            ],
            options={
                'verbose_name_plural': '\u8bbe\u5907\u578b\u53f7',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('male', models.CharField(choices=[(b'male', b'\xe7\x94\xb7'), (b'female', b'\xe5\xa5\xb3')], default=b'male', max_length=10, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hardware.City')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart')),
            ],
            options={
                'verbose_name': '\u5458\u5de5\u59d3\u540d',
                'verbose_name_plural': '\u5458\u5de5',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='hardware.Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='hardware.User'),
        ),
    ]
