# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': '\u8bbe\u5907\u578b\u53f7'},
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(default=b'', max_length=20, unique=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
    ]
