# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_auto_20160629_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='hardware.Type'),
        ),
    ]
