# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_item_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='depart',
            field=models.ForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart'),
        ),
    ]
