# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_auto_20160701_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='depart',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart'),
        ),
    ]
