# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_auto_20160701_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='city',
        ),
    ]
