# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_remove_item_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hardware.City'),
        ),
    ]
