# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_auto_20160701_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe9\x87\x87\xe8\xb4\xad\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
