# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20160701_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_use',
            field=models.NullBooleanField(choices=[(True, b'\xe6\x98\xaf'), (False, b'\xe5\x90\xa6')], default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x9c\xa8\xe7\x94\xa8'),
        ),
    ]
