# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_auto_20160701_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username'], 'verbose_name': '\u5458\u5de5\u59d3\u540d', 'verbose_name_plural': '\u5458\u5de5'},
        ),
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hardware.City', verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82'),
        ),
        migrations.AlterField(
            model_name='item',
            name='depart',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart', verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8'),
        ),
        migrations.AlterField(
            model_name='item',
            name='describe',
            field=models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_use',
            field=models.NullBooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x9c\xa8\xe7\x94\xa8'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='hardware.Type', verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.User', verbose_name=b'\xe4\xbd\xbf\xe7\x94\xa8\xe4\xba\xba'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hardware.City', verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart', verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8'),
        ),
    ]
