# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0014_auto_20160711_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='departname',
            field=models.CharField(max_length=10, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u91c7\u8d2d\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ctitem', to='hardware.City', verbose_name='\u57ce\u5e02'),
        ),
        migrations.AlterField(
            model_name='item',
            name='depart',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='item',
            name='describe',
            field=models.CharField(blank=True, default=b'', max_length=20, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_use',
            field=models.NullBooleanField(default=False, verbose_name='\u662f\u5426\u5728\u7528'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='\u8bbe\u5907\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='item',
            name='suplier',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='hardware.Type', verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hardware.User', verbose_name='\u4f7f\u7528\u4eba'),
        ),
        migrations.AlterField(
            model_name='type',
            name='price',
            field=models.IntegerField(default=0, verbose_name='\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(default=b'', max_length=10, unique=True, verbose_name='\u8bbe\u5907\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hardware.City', verbose_name='\u57ce\u5e02'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.Depart', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='user',
            name='male',
            field=models.CharField(choices=[(b'male', '\u7537'), (b'female', '\u5973')], default=b'male', max_length=10, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='\u59d3\u540d'),
        ),
    ]
