# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_auto_20160711_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hardware.City', verbose_name='\u57ce\u5e02'),
        ),
    ]
